### ISSUE TITLE
Namespace to Gateway - portal new provider experience

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#1017]
This ticket is focused on the `portal new provider experience` / no gateways page.

## Test cases
- upon API provider login with no gateways, from home page, nav to Gateways page:
  - GatewayGetStarted content shows
- after creating a Gateway:
  - GatewayGetStarted content does not show (instead it is Gateways list)
- Write test cases to verify the `gwa` command instructions shown on the page work as desired?

Causes/relates to:
- https://github.com/bcgov/gwa-cli/issues/100
- https://github.com/bcgov/gwa-cli/issues/101
- https://github.com/bcgov/gwa-cli/issues/103

**Comment by rustyjux** [comment]
Design clarifications:
- add more detailed instructions for installing the CLI than just a link to the GitHub releases page? 
  - yes, change to this https://developer.gov.bc.ca/docs/default/component/aps-infra-platform-docs/how-to/gwa-install/ 
- "GWA CLI commands" - shorten text to: `These useful commands will help you manage your gateway resources.`
- `gwa login` - add `gwa config set host http://api-gov-bc-ca.test.api.gov.bc.ca/` 
- remove "Other utility commands" at the end of the page

**Comment by rustyjux** [comment]
The `test your gateway` step - this feels like it is going to be quite involved in one 'step' on this page. I've added more details in https://github.com/bcgov/api-services-portal/commit/c8d7e3d8a83a52bffe8e1c7473e781c652e681f2, but most users would probably be better served by more detailed instructions (including the sample curl commands) like we have in the quick start tutorial.

**Comment by rustyjux** [comment]
Following up on previous comment, we decided to add https://github.com/bcgov/gwa-cli/issues/109 and will add additional text after the process part of the No Gateways/Get Started page along the lines of:
> Congratulations! You have done X now do X

**Comment by rustyjux** [comment]
To make the Getting Started process smooth for users, we will not direct users on `api.gov.bc.ca` to use the test env. 

We will look at what env of the Portal users are viewing and:
- for prod, show no `config set host` command
- for dev (or a feature branch) and test, show the appropriate `config set host` step

Longer term follow-up is needed to plan for keeping the production environment free from excessive test gateways and gw services.
