### ISSUE TITLE
Namespace to Gateway - portal my gateways

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#1018]
This ticket is focused on the new `portal my gateways` page:

<img width="707" alt="image" src="https://github.com/bcgov/api-services-portal/assets/23747270/8c80ed63-421b-4be2-901f-725cea71e86c">

**Comment by Elson9** [comment]
Remaining items:

- [ ] Reduce space after title (header)
- [ ] Remove "New" tag
- [ ] Detail page: redirect to list if no gateway selected
- [ ] Remove "id" from graphql call
- [ ] Sort alphabetically by displayName, secondarily by name
- [ ] Remove check for existance of displayName (assume always exists)
- [ ] Make inaccessible when not logged in (Russell todo)
- [ ] Use global techdocs url
- [ ] On API Provider login, redirect to gateways page

**Comment by Elson9** [comment]
"id" is needed in the graphql call for switching gateways

**Comment by Elson9** [comment]
Separate issue created for last remaining item: #1078
