### ISSUE TITLE
Namespace to Gateway: breadcrumbs on gateways page

### ISSUE THREAD

**Issue by rustyjux** [bcgov/api-services-portal#1046]
Blocker: #1018 

Add breadcrumbs on gateways page to link back to My Gateways
![image](https://github.com/bcgov/api-services-portal/assets/38586679/ed808497-6540-4ffa-a965-e27d536d01bc)

**Comment by Elson9** [comment]
Completed: https://github.com/bcgov/api-services-portal/pull/1073
