### ISSUE TITLE
Namespace to Gateway - Portal UI labelling updates

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#1067]
With the change from `namespace` to `gateway`, the following label changes should be made to the portal:

| Old | New |
| -- | -- |
| Namespace | Gateway |
| Namespaces | Gateways |
| Manage Namespace | Manage Gateway |
| Namespace Access | Administration Access |
| Namespace Actions | Gateway Actions |
| Create New Namespace | Create New Gateway |

Scope:
- `/nextapp` UI pages/components
- "Export report" labelling on backend (see `src/services/report/output`)

**Comment by rustyjux** [comment]
just showing Sodiq the integration

**Comment by rustyjux** [comment]
Also in scope:
| Old | New |
| -- | -- |
| Namespace 'name' (if referenced by name, rather than the actual data) | Gateway 'ID' |
| `namespace.name` (data) | `namespace.displayName`
| page / path `namespace-access` | `admin-access` |

**Comment by rustyjux** [comment]
Every sheet in the gateway report (except the first Gateways sheet) includes a 'Gateway' column with the ID. I propose adding a second column for the display name to all sheets. Ye?

![image](https://github.com/bcgov/api-services-portal/assets/38586679/8d2b582f-a35d-4b09-9617-74c6db64fa72)

**Comment by ikethecoder** [comment]
sure
