### ISSUE TITLE
Namespace to gateway - feature testing

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#1070]
Related to:
- #1067
- #1018
- #1017
- #1020

**As a Github user logging into the portal..**

* When I login with my Github account, I see the Gateways tab, and when I click on it I get the Get Started page but the CLI does not let me create a gateway

**As an IDIR user with existing gateways logging into the portal..**

Steps:
- Go to https://api-gov-bc-ca.dev.api.gov.bc.ca/
- Log in as an API Provider
- EXPECT redirected to `Gateways` tab
- `/gateways/list` should render the top part immediately, with the row space having a skeleton:

<img width="1228" alt="image" src="https://github.com/bcgov/api-services-portal/assets/23747270/12e0b851-6af8-4c17-82d3-d3c2054a71ae">

- Selecting a gateway for the first time does not redirect you to the `detail` page
- Breadcrumb seems to make a "currentNamespace" call every time you navigate to a different page - is it necessary?
- Gateway selector sometimes makes an API call with `/admin/switch/undefined`, and fails to switch to gateway
- Rendering of the Gateway title information is slow

**As an IDIR user with no gateways logging into the portal..**

- External links to techdocs are broken for the `gwa cli` and the `production checklist`
- Text for "Use the test environment: Configure the CLI to run against a test environment while you are getting familiarized with the API Services Portal." should be more generic as it could be dev or test - maybe something like: "Configure the CLI to run against this environment while you are getting...".
- Command `gwa generate-config --template basic-service` gives the error `Error: required flag(s) "service", "upstream" not set` and `basic-service is not a valid template`

**As an IDIR user I want to delete a gateway**

- Deleting a gateway results in an error and console error `Cannot read properties of null (reading 'displayName')`:
<img width="1209" alt="image" src="https://github.com/bcgov/api-services-portal/assets/23747270/43c88a57-f833-4259-a18e-64f03d7151e5">

**Comment by rustyjux** [comment]
The pile of HTML returned from some `gwa` commands is the result of trying to hit a /v2/ endpoint that doesn't exist, e.g. https://api-gov-bc-ca.dev.api.gov.bc.ca/ds/api/v2/gateways. This is resolved by changing `GWA_VERSION` in .env to v3.

Should improving the handling of this type of error happen in the cli or in the API? or neither since it isn't easy for users to users to alter the API version?

**Comment by ikethecoder** [comment]
Yeah, I think on the CLI if `content-type: text/html` is returned then there's no point in showing the output as it is most certainly garbage.  But the Portal should also use the `Accept` header to return JSON if it is set to `application/json`.

**Comment by ikethecoder** [comment]
Also to consider for gateway services, `gwa-api` does not have a `v3` of its API, so https://github.com/bcgov/api-services-portal/blob/feature/ns-to-gw/src/api-proxy.js#L20 will need to map `/gw/api/v3` to `/v2`.  Otherwise it will probably give a `404` error.

**Comment by ikethecoder** [comment]
> The pile of HTML returned from some `gwa` commands is the result of trying to hit a /v2/ endpoint that doesn't exist, e.g. https://api-gov-bc-ca.dev.api.gov.bc.ca/ds/api/v2/gateways. This is resolved by changing `GWA_VERSION` in .env to v3.
> 
> Should improving the handling of this type of error happen in the cli or in the API? or neither since it isn't easy for users to users to alter the API version?

If people upgrade their `gwa`, are they going to have to manually edit the .env file to `v3`?  Perhaps the `gwa` command line should update this for you.

**Comment by rustyjux** [comment]
> If people upgrade their `gwa`, are they going to have to manually edit the .env file to `v3`? Perhaps the `gwa` command line should update this for you.

I haven't done any builds yet but I'm guessing the .env contents get packed up somewhere. I'll see if I can add general handling for `content-type: text/html` - the HTML response you'd have seen isn't actually total junk (it includes a 404 message), but we should be able to handle that much more cleanly.

**Comment by rustyjux** [comment]
Fixed the http error handling to give `Error: received HTML error page (status code 404)` instead of a wall of text - https://github.com/bcgov/gwa-cli/commit/5b6c3cc9c1726a260d530cd38a09b9779691918d

And I checked out `just release` locally and can confirm the executables created point to the API set in .env. For production releases, we set the .env defaults in the GHA - https://github.com/bcgov/gwa-cli/blob/5b6c3cc9c1726a260d530cd38a09b9779691918d/.github/workflows/main.yml#L11
```
env:
  GWA_API_HOST: api.gov.bc.ca
  GWA_CLIENT_ID: gwa-cli
  GWA_VERSION: v2
```

**Comment by ikethecoder** [comment]
Regression testing
