### ISSUE TITLE
Namespace to Gateway - Error messaging updates on Portal

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#1072]
There are various error and informative messages that are generated in the Portal that reference "namespace".  These should be updated to be "gateway".

The sibling of this ticket is #1067 which is focused on the UI specifically (under `nextapp`).  The majority of messages come from validation rules on the backend.

Scope:
- include both Cypress and backend changes at same time
- all `namespace` references in `ValidationError` exceptions and other validation rules and messages

Technical recommendations: Perhaps branch off `dev` where cypress is passing, make these changes and then merge them in the `feature/ns-to-gw` branch afterwards.

**Comment by rustyjux** [comment]
Though a PR has been merged there are still error messages returned by `gwa-api` which include namespace. E.g. the message when trying to publish a service with a host name which is already in use in another namespace.

Not sure the urgency or effort of making updates to gwa-api to capture those messages.
