### ISSUE TITLE
Namespace to Gateway: Namespace reference in Enable Product environment tooltip

### ISSUE THREAD

**Issue by timng-bcgov** [bcgov/api-services-portal#1114]
# API Services Portal Issue

### ENV

- [x] `DEV`
- [ ] `TEST`
- [ ] `PROD`

### TESTCASE

When enabling an API for discovery on the Portal UI, users navigating to the Gateway -> Products -> Edit environment modal dialog encounter an 'Enable environment' checkbox. When the Gateway does not have an associated Organization and Business Unit, the checkbox is disabled and hover interactions trigger a tooltip.

### EXPECTED

The tooltip should display "Available after an Organization has been associated to your Gateway".

### ACTUAL

The tooltip displays "Available after an Organization has been associated to your namespace".
<img width="1412" alt="Configure environment modal with Enable environment disabled tooltip" src="https://github.com/user-attachments/assets/65773621-3f4a-4f12-9eb2-dc2c4c8f9df7">

**Comment by rustyjux** [comment]
closed in https://github.com/bcgov/api-services-portal/commit/41ad7309c0817ca940a52ebec1aaad40cc2414eb
