### ISSUE TITLE
Kong ACL Only Flow should not be marked active

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#128]
Update the Environment Activation validation to generate an error if the `kong-acl-only` flow is used.  There is not support for this flow on the Directory / Requesting Access.  It is used in conjunction with the "Link Consumer to Namespace" feature to cover the scenario where users are protected with an auth plugin that is outside the scope of the Portal.

**Comment by nirajCITZ** [comment]
The defect is resolved with latest PR(#418)..I verified and it's working fine
