### ISSUE TITLE
When collecting credentials, the alert messaging can be incorrect if after a failed attempt

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#139]
# API Services Portal Issue

## User Story

**As a** Developer,<br>
**I want** to request access to an API<br>
**so that** I can use it.

### ENV

- [X] `DEV`
- [ ] `TEST`
- [ ] `PROD`

### TESTCASE

- Define an API that has "Approval Required" and that uses an Authorization Profile that you know is misconfigured
- Request access to the API
- Generating credentials will fail as expected
- Go back to the My Access page; the request should be under the "Collect Credentials" alert
- Click the request 

### EXPECTED

- Expect to the see the alert that states the request is pending approval

### ACTUAL

- You see the message: "Request Processed: Your credentials are ready and authorized to access the API."

### ERROR

This is happening because the `isComplete` gets set to `false` when an error is detected but the query to get all pending AccessRequests uses: `where: { isComplete: null }`.

**Comment by Jonesy** [comment]
@ikethecoder Should we only query for `isComplete: false` access request then? I don't know which auth profiles are incomplete to test against in dev, if you know of one could you comment it here?

**Comment by Jonesy** [comment]
Closing this issue because this is being worked on in the `feature/auth-profiles-ui` branch.
