### ISSUE TITLE
UI changes - Namespaces homepage

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#153]
Address the following:

- User interface (buttons, links, and visual styling)
- Interaction design
- Labels, headlines, and written text
- Navigation structures and content classification
- Accessibility (contrast, visual focus indicators, text alternatives, etc.)

**Comment by elisafw-ux** [comment]
Link: https://www.figma.com/file/LdBNHPjD3mlIggDrGYljs9/API-Services-Portal?node-id=1489%3A383

**Comment by ikethecoder** [comment]
Examples of the Scopes (Roles look the same) on the Access Request page and the Consumer Detail page.

![Screen Shot 2021-08-20 at 4.44.10 PM.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/fce7175f-03f3-48f8-93c0-caaf71a194c6)![Screen Shot 2021-08-20 at 4.44.33 PM.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/14660a84-1714-4b63-8d75-1159ac239133)
