### ISSUE TITLE
Application version number design

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#162]
Determine where to place application version number

**Comment by elisafw-ux** [comment]
![Screen Shot 2021-11-30 at 2.38.11 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/9be1b3cb-66c2-4e8d-8c99-0e61c0a7bd30)

Design found under "Other States" in Figma https://www.figma.com/file/LdBNHPjD3mlIggDrGYljs9/API-Services-Portal?node-id=1797%3A887

**Comment by ikethecoder** [comment]
@elisafw-ux can we incorporate a substring of the Revision (https://api.gov.bc.ca/about) and maybe some subtle indication for `cluster`.

**Comment by Jonesy** [comment]
I've added a tooltip for now ![image.png](https://images.zenhubusercontent.com/5c58b4fbecb0076f3e898867/e7214ce1-56b2-42c9-9058-62a5c03890be)
