### ISSUE TITLE
Plugin Edit not backfilling the Service or Route

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#167]
# API Services Portal Issue

## User Story

**As a** Access Manager,<br>
**I want** to modify the ip restrictions and rate limiting settings for a consumer<br>
**so that** the gateway enforces the proper controls.

### ENV

- [X] `DEV`
- [X] `TEST`
- [X] `PROD`

### TESTCASE

- Add a Rate Limiting and IP Restrictions plugin to a Consumer
- Then click the Edit button for the particular control

### EXPECTED

- The Service/Route to be backfilled with the service/route for the record

### ACTUAL

- The Service/Route defaults to the first item in the dropdown

**Comment by Jonesy** [comment]
@ikethecoder I think the issue is because the `id` is being passed as the value for the select, but it looks like the option values are using `extForeignKey`. I changed added `extForeignKey` to the query and pass that in now, let me know if that is correct behaviour.

**Comment by ikethecoder** [comment]
Yep, that is correct.
