### ISSUE TITLE
Create Test to Publish a Service to Kong Gateway

### ISSUE THREAD

**Issue by NithinKuruba** [bcgov/api-services-portal#173]
**Description**

Tests API Owner creating an API

**Prerequisites**

- Template for generating API: `fixtures/service.yml`
- Client ID and Secret generated and stored in `fixtures/state/store`

**Test Steps**

Note: This is a general outline;`publishAPI` command in `support/auth-commands.ts` accomplishes this:

1. Load client ID and secret from `fixtures/state/store`
2. Generate an access token (`getAccessToken` method can be used) with ID/secret
3. Get access token response and and send PUT request to publish contents of `service.yml`

** Test Data**

- `fixtures/service.yml` for API templates
- Client ID and Secret generated and stored in `fixtures/state/store`

**Expected Results**

- API created successfully and available in API Directory

**Comment by jTendeck** [comment]
Test case has been implemented - need to merge into dev.
