### ISSUE TITLE
Ability to define additional claims that are attached to new clients credentials

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#196]
# API Services Portal Issue

## User Story

**As a** API Owner,<br>
**I want** to be able to define additional claims, such as Audience, when defining an Authorization Profile<br>
**so that** they can be included in new Client credentials created during the Access Request process.

### ENV

- [ ] `DEV`
- [ ] `TEST`
- [ ] `PROD`

**Comment by elisafw-ux** [comment]
![Screen Shot 2021-10-05 at 1.09.37 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/1d19f181-dc93-4845-8015-53bd49bcecfa)
This is the design when there's only one client mapper option. As more options get added, the "disabled" client mapper field will become a dropdown. There will also be an "Add" button to add more client mappers.

**Comment by ikethecoder** [comment]
Note: The IdP needs to have a policy that allows Audience to be added as a Protocol Mapper to the client.

Otherwise there will be the error: `Policy 'Allowed Protocol Mapper Types' rejected request to client-registration service. Details: ProtocolMapper type not allowed`

In Keycloak, this is updated under the Realm's `Client Registration -> Client Registration Policies`.

Edit the `Authenticated Access Policies` -> `Allowed Protocol Mapper Types` to include the `oidc-audience-mapper`.
