### ISSUE TITLE
Organization Unit not visible in Products

### ISSUE THREAD

**Issue by jTendeck** [bcgov/api-services-portal#227]
# API Services Portal Issue

### ENV

- [x] `DEV`
- [ ] `TEST`
- [ ] `PROD`

### TESTCASE

1. Spin up dev env and log in (awsummer@idir was used)
2. Switch to existing namespace, or create namespace and switch to it if needed
3. Navigate: Namespaces > Products
4. Create a Product if none exist
5. Click `Edit` next to Product (not environment)
6. Provide Name if needed, select an Organization (Ministry of Health selected in this case), then select Organization Unit

### EXPECTED

- Organization Unit should be visible and selectable in dropdown. For our test cases, this is Planning and Innovation Division

### ACTUAL

- Planning and Innovation not available in the Organization Unit dropdown

![image.png](https://images.zenhubusercontent.com/613f7c586dae559942cbbc64/d4f87270-f65e-47f4-8359-f88b83c6aa07)

### ERROR

403 error in console when clicking on the Organization Unit dropdown

**Comment by ikethecoder** [comment]
This can be closed because we have removed Org and Org Unit from the Product detail page.
