### ISSUE TITLE
IP Restrictions, Rate Limiting Test

### ISSUE THREAD

**Issue by jTendeck** [bcgov/api-services-portal#231]
The API Owner can add IP restrictions and rate limiting to Consumer access. Need to add these restrictions and then test that they are applied when making API requests.

Also need to test removing these restrictions and that API calls no longer have these restrictions after removing.

TODO add in steps for test case when Unexpected Errors are resolved.

**Comment by JohnathanBrammall** [comment]
I believe this has been implemented and this ticket can be closed. @jTendeck  @nirajCITZ  Please confirm.
