### ISSUE TITLE
Cannot create authz profile even after assigning Credential.Issuer admin scope but requires re-login after assigning the scope to create the same

### ISSUE THREAD

**Issue by NithinKuruba** [bcgov/api-services-portal#237]

**Comment by ikethecoder** [comment]
This is true, in the sense that the authorization check for the Portal functionality is done at the time of switching to a namespace.

But a few things to consider:
* Should a user be able to change permissions related to themselves?
* Should changes in permissions invalid sessions for that particular User?

**Comment by NithinKuruba** [comment]
One easy way to address this is to let users know through a notification dialog or alert that they need to re-login for new permissions to take effect.

**Comment by ikethecoder** [comment]
Feature branch: `feature/issue-237-access-stale`
