### ISSUE TITLE
Planned Maintenance Page

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#241]
When the Portal is configured with a Disaster Recovery scenario, it may be required to let the user know that the site is unavailable.

**Comment by elisafw-ux** [comment]
![Maintenance Banner.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/a999ac9e-7923-4f7c-a041-1ea778aa9092)

Design specs and interaction notes found under "Down for maintenance alert": https://www.figma.com/file/LdBNHPjD3mlIggDrGYljs9/API-Services-Portal?node-id=1797%3A887

BC Design system on alert banners: https://developer.gov.bc.ca/Design-System/Alert-Banners
