### ISSUE TITLE
Design menu when logged in with business BCeID

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#283]
![Screen Shot 2022-01-07 at 1.23.01 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/0a80a9da-fc22-4767-b943-6a63fcf407dd)

As per https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/identity-and-authentication-services/login-best-practices/government-website-headers 

when a user is logged in with Business BCeID, display their business name

**Comment by elisafw-ux** [comment]
![Logged in with Business BCeID.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/49937685-5fd4-4a55-a0fe-93b7ab074c8b)

![Logged in with IDIR or Github.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/163b912d-58c8-43a0-bb41-eb0423639aca)

**Comment by ikethecoder** [comment]
@elisafw-ux can we include here the convention for "display name" for IDIR and Business BCeID.  For example, for IDIR, it gets pulled through as this:

![Screen Shot 2022-01-14 at 9.46.56 AM.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/14b103e8-9f60-47db-83f5-2bb8ebaa4035)

**Comment by elisafw-ux** [comment]
@ikethecoder for the avatars we can follow the convention. But do you also mean following the convention for the menu when an individual hovers over their name?
