### ISSUE TITLE
About Us page content

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#294]
The API Services Portal does not provide context or description of the value that APS' services provide. Users and potential clients trying to understand our services need information to help them navigate their use of the API Services Portal. 

Questions to be answered: 
 - Where will this content be shown on the API Services Portal
 - What initial content needs to be present and how will it be presented

Constraints: Content about APS needs to remain consistent with other documentation such as the 2-pager value proposition document (currently in draft) and the content in the CMS Lite page. 

Out of scope: Content does not need to be consistent with developer.gov.bc.ca content about APS until after that platform has been refreshed. Work on that content will be drafted to align with the content created in this work.

Definition of Done: Initial content is provided about APS Services on the API Services Portal so that users can self-serve this information.

**Comment by elisafw-ux** [comment]
- We'll be showing this content on the About Us page accessible through the footer
- Content is consistent with the 2 pager value proposition doc

![Screen Shot 2022-08-24 at 11.03.58 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/163ac98c-4962-411c-a178-86f45d5c194e)

**Comment by elisafw-ux** [comment]
@JohnathanBrammall please review ticket. Thanks!

**Comment by JohnathanBrammall** [comment]
Looks great. Thanks @elisafw-ux

**Comment by JohnathanBrammall** [comment]
With respect to content, can we update the first sentence reference to APS to match our new definition in the glossary?

**Comment by elisafw-ux** [comment]
I've replaced the text to match our glossary.
