### ISSUE TITLE
Consumers Access Request

### ISSUE THREAD

**Issue by Jonesy** [bcgov/api-services-portal#326]
UI is needed to display incoming access requests, open them in a dialog to review details, add controls or authorization rules and ultimately approve or reject the request.

![image.png](https://images.zenhubusercontent.com/5c58b4fbecb0076f3e898867/311a5578-5a5d-46bf-a65c-4105f5746caa)

![image.png](https://images.zenhubusercontent.com/5c58b4fbecb0076f3e898867/730e172b-5ab6-40bb-b410-2cc9b39f6d70)

**Comment by ikethecoder** [comment]
Duplicate - closing
