### ISSUE TITLE
Refresh credentials by approved consumer

### ISSUE THREAD

**Issue by JohnathanBrammall** [bcgov/api-services-portal#332]
As an API Consumer (Harley), I want to be able to receive updated credentials without having to wait for a second approval by the API Provider so that I can continue with already approved use of an API. As an API Access Manager (Mark), I want to automate re-issue of lost credentials so that I am not re-issuing credentials that have already been approved.

Scenarios where this may arise:

- Harley has lost or forgotten the access credential (e.g. API key) provided when access was requested.
- Harley or Mark believe the credential has been appropriated by another user and needs to be changed.
- Mark or Harley have business reasons for periodic renewal of an access credential (e.g. API key).

Constraints: 

- As an API Provider I want an assurance that the individual requesting the new key is the same consumer or application representative (in case of changes in staff) that was originally approved.
- As an APS team member I do not want keys shared or transmitted to any more individuals than is necessary or easily shared beyond using our system. 

**Tasks**

* [x] Prototype 
* [x] Client/team feedback
* [x] Implementation

**Comment by elisafw-ux** [comment]
![My Access.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/919a5623-7daf-4345-bf89-20bdf84f1e96)![My Access (1).png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/40991516-58c7-4590-b729-e2f56ee6531c)![My Access (2).png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/20130f7d-6cff-4be1-a3b4-a2ff2fbbc7c7)

**Comment by elisafw-ux** [comment]
@ikethecoder @JohnathanBrammall Please review. The screens are in order starting at the top.

**Comment by JohnathanBrammall** [comment]
@elisafw-ux looks great. I like that you've covered the pending approval use case as well.

**Comment by JohnathanBrammall** [comment]
Agreed. Simple and easy to use. Ready to move to implementation. Moving Epic to Product Backlog for prioritization. Development and Implementation tickets to be created.

**Comment by ikethecoder** [comment]
This was completed in April
