### ISSUE TITLE
The pending request does not get displayed to Access Manager when only 'Access.Manager' permission is assigned to Access Manager

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#333]
Step:
1) API owner (Janis) assign only 'Access.Manager' and 'Namespace.View' permission to Mark
2) Harley create a API access request
3)Janis revoke assign only 'Access.Manager' request to Mark
4) Mark sign in the application to approve the pending request

Actual Result : The pending request does not get displayed to Access Manager when only 'Access.Manager' permission is assigned to Access Manager

Expected Result : The pending request should be displayed to Access Manager when only 'Access.Manager' permission is assigned to Access Manager

**Comment by mwendowsky** [comment]
impacts way that we look at different roles in platform, linked to access manager testing scenarios

**Comment by nirajCITZ** [comment]
The defect is fixed with the latest PR (#418)...I verified and it's working fine
