### ISSUE TITLE
Test - Content.Publish Permission

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#340]
1. Verify Content Publish Permission
1.1 authenticates Janis (api owner)
1.2 Get the authorization token for the service account created with out "Content.Publish" permission
1.3 Prepare the Request Specification for the API
1.4 Verify that the document is not published without "Content.Publish" permission

**Comment by mwendowsky** [comment]
@nirajCITZ to flesh out ticket if has time
