### ISSUE TITLE
Improve the Access Request experience for unauthenticated users

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#344]
**Description**: As a Developer, I want to have clear instructions on what authentication method I can use to request access to an API, so that I can make a request as easily as possible.

**Current Behaviour**: An "Unauthorized" page is displayed with a "Login" button, which is confusing for the user:

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/f31a26f2-415a-467e-84cb-efe9e2a426c2)

**New Design**: Prompt the user to select the authentication method if they are not logged on:

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/6db4934b-c2ed-48bc-8c1b-f7b7bc03cf1f)

UX/UI Design - #220

**Comment by Jonesy** [comment]
This feature is part of PR #385
