### ISSUE TITLE
System does not generate Secret for the API having Client Credential authorization flows

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#347]
When Harley raise request for the API having client credential authorization flow and Generate secret by click on 'Generate Secret' button under My Access page then system displays following error.![Screen Shot 2022-03-17 at 11.57.33 AM.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/3d1a47e6-44bd-4ac2-97a0-a187cd633014)

Attached is the APS-portal log file[https://app.zenhub.com/files/322371232/f31e2e29-b6ea-4f44-ae2d-7d5f4ae35bf1/download](https://app.zenhub.com/files/322371232/f31e2e29-b6ea-4f44-ae2d-7d5f4ae35bf1/download)

**Comment by mwendowsky** [comment]
blocking Niraj in updating cypress scenarios

**Comment by JohnathanBrammall** [comment]
Error appears to be occurring locally, need to investigate the cause.

**Comment by JohnathanBrammall** [comment]
This appears to have been fixed in the work for the Portal release v. 1.1
