### ISSUE TITLE
System does not generate authorization profile for 'Kong API Key' authorization flow

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#349]
Step:
1)Sign in to the user who has access to create authorization profile
2)Click on 'Authorization Profiles' option in Namespace page
3)Click on 'Create New Profile' button 
4)Enter any profile name in the pop up and click on Continue button
5) Select 'Kong API Key' authorization flow option and enter Key name
6) Click on Create button

Actual Result : System displays 'Profile create failed' error message

![Screen Shot 2022-03-11 at 1.01.18 PM.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/da3b70cf-7b99-4707-a819-ea4fe96a322d)

**Comment by JohnathanBrammall** [comment]
we will be retiring Kong API key as an option for Authorization Profile options for users. The functionality will be available through the API but will not be available through the UI, which is where the bug resides.
