### ISSUE TITLE
Credential Refresh UI implementation

### ISSUE THREAD

**Issue by JohnathanBrammall** [bcgov/api-services-portal#367]
Implement the following UI into the API Services Portal

![My Access (3).png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/8511beac-c7bc-4057-9a67-e613afc9b243)
![My Access (4).png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/e971ce19-6b94-40d4-bd1f-a7e2efd8cf2c)
![My Access (5).png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/ae3f6f3f-2481-4fb3-9dc7-60bf83e8279d)

In the case of a pending request, Harley can regenerate credentials if he forgot to copy the secrets and closed the dialog even though there is warning, Harley should still have an option to correct his mistake by regenerating credentials.

**Comment by JohnathanBrammall** [comment]
@Jonesy Do you need any further info in this ticket to complete the work?

**Comment by Jonesy** [comment]
@JohnathanBrammall I may possibly need some details from @ikethecoder , will reach out and confirm when I start work.

**Comment by ikethecoder** [comment]
Regenerate Credentials is only valid for the flows client-credentials, kong-api-key-acl and kong-api-key-only.  In the case of client-credentials, the Authorization Profile Authenticator must be `client-secret`.
