### ISSUE TITLE
Documentation re-design for API Services Portal

### ISSUE THREAD

**Issue by JohnathanBrammall** [bcgov/api-services-portal#378]
Thought-spike: initial thoughts and design for incorporating Retype into the documentation offerings on the API Services Portal.

Context:
 - evolving government design and content standards
 - ease of maintenance
 - ability to find content specific to needs

**Comment by ikethecoder** [comment]
No update for 9 months.  People seem to be happy with the Retype documentation we have off of the Help dropdown.  A new ticket can be created to address any new concern.
