### ISSUE TITLE
API Test - Get aggregated information about namespaces

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#384]
1. Get the user session token to pass it as authorization token to make the API call
1.1 authenticates Janis (api owner) to get the user session token
2. API Tests for Namespace Report
2.1 Prepare the Request Specification for the API
2.2 Get the resource and verify the success code in the response
3. API Tests for Namespace List
3.1 Prepare the Request Specification for the API
3.2 Get the resource and verify the success code in the response
3.3 Verify that the selected Namespace is displayed in the Response list in the response
4. API Tests for Namespace Activities
4.1 Prepare the Request Specification for the API
4.2 Get the resource and verify the success code in the response
5. API Tests for Deleting Namespace
5.1 Prepare the Request Specification for the API
5.2 Delete the namespace and verify the success code in the response
5.3 Verify that deleted namespace does not display in Get namespace list

**Comment by mwendowsky** [comment]
blocked due to two defects
