### ISSUE TITLE
Draft / Preview Mode

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#387]
**Story**: As an API Owner, I want to be able to preview my products on the API Directory before they get published so that I can verify that requesting access works correctly.

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/ef95e382-0738-4338-b500-45f443863afa)

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/ec5c39af-9b6b-49c1-9c24-dbbe51dc5fc1)

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/49443ff8-797f-4ad1-967f-671fa3ea8899)

**Comment by Jonesy** [comment]
Remaining items left for this issue:

- [ ] A property on the product API record that signals it's in draft mode (via @ikethecoder )
- [ ] JSM link (should be coming this week via @elisafw-ux )
