### ISSUE TITLE
Footer in Namespaces page cuts off

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#388]
Steps to reproduce:

- Choose a namespace
- Navigate to the Namespaces page

![Screen Shot 2022-05-17 at 12.18.59 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/c5d1f174-992b-4ba6-a007-70c91e35a307)

**Comment by Jonesy** [comment]
@elisafw-ux I can't recreate this, is it cutoff from scrolling or just how it appears on your monitor (and you can scroll)? Which browser and environment are you seeing this also?

**Comment by elisafw-ux** [comment]
I should've mentioned, when I scroll I can see it but it just gets cut off in my viewport. I need to scroll to see the rest of the footer. I am using Chrome - in test env.
