### ISSUE TITLE
Ministries / Organizations UI

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#389]
**Todo**: split this story into smaller parts based on when we do estimations.

Organizations page:

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/53126df6-1438-406a-8311-2644dfc3557f)

Namespaces tab:

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/d207bf1e-1021-41e3-a46e-a3744f7ec484)

Roles tab:

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/ce6f0aab-2486-491d-9b6b-2e82e845cc15)

Role tab:

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/0d86be0d-3575-4d53-b496-30ab2176f802)

**Comment by mwendowsky** [comment]
to be updated based on Elisa's new design work
