### ISSUE TITLE
Not clear when requesting access for an application that has already requested access

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#421]
# API Services Portal Issue

## User Story

**As a** Developer,<br>
**I want** to request access to an API using an Application<br>
**so that** I can start to use the API.

### ENV

- [ ] `DEV`
- [ ] `TEST`
- [X] `PROD`

### TESTCASE

- Request access to an API for a "dev" environment using Application "test app"
- Request access to the same API, environment and Application

### EXPECTED

- Expect to be told that I have already requested access for the Application

### ACTUAL

- It lets me create the request and when I generate credentials it just gives the error "Unable to generate keys"

**Comment by nirajCITZ** [comment]
The defect is fixed with latest PR (#418).I verified this defect and it's working fine
