### ISSUE TITLE
The API Provider card on the homepage doesn't link to anything when no namespace is selected

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#426]
The "For API Providers" card on the homepage doesn't link to anything when a user is logged in and no namespace is selected. 

Design an empty state UI with the message "no namespace is selected, please select one" 

* [x] Design
* [ ] Implementation

**Comment by elisafw-ux** [comment]
@Jonesy The design for this issue is ready on Figma under the namespace homepage section.

![No namespace selected empty state.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/f33def6a-e341-453d-bec6-864c365f531d)

When to display

- When a user is logged in, no namespace is selected, and clicks on the API Provider card in the “homepage”
- Once a namespace is selected, show the current toast confirmation that says "switched to ABC namespace" at the bottom and take the user to the namespace dashboard of the
selected namespace

**Comment by ikethecoder** [comment]
Should there be an option to Create one?  As a first time user, the pick list might be empty.
