### ISSUE TITLE
Collect email for notifications

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#452]
**Story**: As a Developer that logs in with an Identity Provider that does not provide Email, I want to provide an email so that I can be notified when my request for access has been approved.

* [x] Design
* [x] Implementation

Test Scenarios:
1. BCSC user login for the first time and email updated: Confirm the user is prompted with dialog to update email, and that the email was updated
2. BCSC user login for the second time : Confirm no prompt for email and previously updated email appears in Profile
3. IDIR user login for the first time : Confirm user's email is set from Identity Provider and not prompted to change and no Edit email on profile
4. IDIR user login for the second time : Confirm no prompt for email
5. BCSC user login for the first time from the Request Access flow and is prompted for email : Confirm the user comes back to the Request Access page with the Email update dialog; and after update, remains on the Request Access page

**Comment by elisafw-ux** [comment]
Designs on Figma under "Login with BCSC"

**Comment by elisafw-ux** [comment]
![Screen Shot 2022-07-21 at 2.46.10 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/3273f22d-71b4-4cda-93c0-41b811037f27)

**Comment by Jonesy** [comment]
On hold until API support is available for editing user's email

**Comment by ikethecoder** [comment]
@elisafw-ux If a user edits their email address in the Portal, does that always override whatever email is passed from the identity provider?  For example, I log in with my Gov ID and it has email "myself@gov" and then in the Portal I update my email address to "personal@gmail.com".. what should we do with future email addresses that come from the Gov ID?  Should we only allow setting of the email for Identity Providers that do not pass us email?

**Comment by ikethecoder** [comment]
@Jonesy I've added an `updateEmail` GraphQL call - you can see it wired up on the User Profile page.

Note: When the Complete Profile dialog appears, you can't close it so you are kind of stuck there if you don't want to update the email.

**Comment by Jonesy** [comment]
Fixed @ikethecoder , I'll make a PR if there's nothing else left to add to this story
