### ISSUE TITLE
Mark can Grant Access to the service for the environment which is pending for approval

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#475]
Step 1: Harley raise Access request for the service (say 'Auto Test Product') for the environment (say 'Dev)
Step 2: Mark login to the application
Step 3: Select the namespace
Step 4: Navigate to the consumer page
Step 5: Verify he can see the banner to approve the pending request
Step 6: Click on the Consumer ID which was created by Harley in above steps
Step 7: Click on Grant Access button
Step 8 : Select the product as 'Auto Test Product' and environment as 'Dev' and click on Grant Access button

Actual Result : Mark can Grant Access to the service for the environment which is pending for approval. 

Expected Result : 
1)Mark should not be  allowed to Grant Access to the service for the environment which is pending for approval
2)Mark should not be  allowed to Grant Access to the service for the environment which is already approved
3)Mark should only be able to grant access using an already approved credential

Environment - Local docker container

**Comment by chrsamp** [comment]
@Elson9 @jTendeck Possibly another good bug fix ticket

**Comment by odyeung** [comment]
related to access manager

**Comment by ikethecoder** [comment]
Implemented this toast error whenever a user tries to perform any actions against the consumer while there are pending access requests for that consumer:
<img width="589" alt="image" src="https://github.com/bcgov/api-services-portal/assets/23747270/2173057f-d69d-461d-a2af-a0e7334318ce">

**Comment by BrandonSharratt** [comment]
This seems to be fixed I was able to do it but am no longer able to do it after updating to newest version
