### ISSUE TITLE
Display the identity provider in the requester's info on the access request modal

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#479]
Identify the requester's identity provider (IDIR, BCSC, etc) in the requester's information (top right of the access request modal) as we can't assume that the username ends with an idir

![Screen Shot 2022-08-04 at 11.22.52 AM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/5c9849f7-10ad-4c14-896c-e722fe76adb6)

DoD: a design that displays the identity provider 

* [x] Design
* [ ] Implementation

**Comment by elisafw-ux** [comment]
Design specs:

![Requester Info Cards.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/fb0d26c5-088f-4f26-a796-1df921edae9d)

**Comment by elisafw-ux** [comment]
@JohnathanBrammall @ikethecoder @Jonesy please review ticket :)

**Comment by JohnathanBrammall** [comment]
This looks great. Thanks @elisafw-ux

**Comment by elisafw-ux** [comment]
@Jonesy ready for implementation
