### ISSUE TITLE
Next direct links to documentation fails due to missing object

### ISSUE THREAD

**Issue by Jonesy** [bcgov/api-services-portal#480]
Links from https://www2.gov.bc.ca/gov/content/data/about-data-management/databc/databc-products-services/api-management to the APS Portal website throw errors when visiting directly. They can be worked around by visiting the Documentation tab then visiting the link after.

Problem URL: https://api.gov.bc.ca/docs/platform-api-owner-user-journey

The error seems to be thrown by the document object being undefined while trying to access the `title` property.

**Comment by ikethecoder** [comment]
@chrsamp The documentation tab is no longer on the portal, so these external links should be fixed.

Link | New URL |
| - | - |
| API Provider User Journey | https://bcgov.github.io/aps-infra-platform/guides/owner-journey |
| APS Release Notes | https://bcgov.github.io/aps-infra-platform/releases |
