### ISSUE TITLE
Managing public keys for signed jwt

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#518]
## User Story

**As a** API Provider,<br>
**I want** a way for my clients to provide (and self-serve) a public certificate during access request time <br>
**so that** my Identity Provider can use it to validate the Client Assertion Token <br>
**unlike now** where the only option currently is to use the `Signed JWT with JWKS URL` which is not possible as our IdP does not have direct internet access.

## Notes

We have implemented the calls to the IdP already as we use it for the `Signed JWT with Generated Key Pair` flow.

Expected changes:
* Add a new `authenticator` of `signed-jwt-with-public-key` on the Authorization Profile
* On the Access Request dialog, prompt the user for a valid Public Key
* Use the public key as part of the Client creation
* Expose an API that allows an Application Owner (Consumer) to update their Public Key
* Provide a way for a Consumer to create an API Key for themselves for calling the above API

**Comment by elisafw-ux** [comment]
[Designs (discussion board)](https://www.figma.com/file/00SZt0Ezx1DGz1x1tlcNLL/APS-Portal-Designs?node-id=29122%3A16740&t=1lK1LZPteRbsNC9w-1)

**Comment by elisafw-ux** [comment]
@ikethecoder sorry! it's the same issue where you are gone from the board. I've invited you to view.

**Comment by sienna-blumstengel-bcgov** [comment]
@elisafw-ux to chat with Aidan to verify that there is anything else to work on

**Comment by elisafw-ux** [comment]
@ikethecoder On the access request modal, I left the UI how it was originally by including the public key under the environment then a text area for people to add their public key in PEM format. Under the My Access page I removed "Regenerate Credentials" and just have "Update Public Key"

Is there anything else that I need to work on from the UI side?

**Comment by elisafw-ux** [comment]
@chrsamp @ikethecoder [Please review designs](https://www.figma.com/file/00SZt0Ezx1DGz1x1tlcNLL/APS-Portal-Designs?node-id=29122%3A16740&t=ZUPCE7I5bFjdHzbs-1)

**Comment by elisafw-ux** [comment]
@chrsamp @ikethecoder [Updated designs](https://www.figma.com/file/00SZt0Ezx1DGz1x1tlcNLL/APS-Portal-Designs?node-id=29122%3A16740&t=677K0OEOgSJ9vyHX-1) Please review.

**Comment by chrsamp** [comment]
@elisafw-ux Reviewed and looks good to me. Makes sense to combine the public cert/JWKS options on the access request.
