### ISSUE TITLE
Error and success messages for when a user tries to activate an environment

### ISSUE THREAD

**Issue by sienna-blumstengel-bcgov** [bcgov/api-services-portal#547]
### User story
As a user, I want to know if my attempt to activate an environment was successful or not, and why, so that I know what to do next.

### Acceptance Criteria

**Scenario 1: Fail because namespace has not yet been approved/added to an org**
* **GIVEN** an API provider has created a namespace and environments in that namespace
* **AND** the namespace has **not yet been approved/added to an org** (by the org admin or by the APS team)
* **WHEN** the API provider attempts to activate an environment under that unapproved namespace
* **THEN** an error message displays, and provides the API provider with helpful info

**Scenario 2: Success because namespace has been approved/added to an org**
* **GIVEN** an API provider has created a namespace and environments in that namespace
* **AND** the namespace has **HAS** been approved/added to an org (by the org admin or by the APS team)
* **WHEN** the API provider attempts to activate an environment under that unapproved namespace
* **THEN** an the API provider is shown a success message

**Scenario 3:** ???
* **GIVEN** 
* **WHEN** 
* **THEN**

**Comment by elisafw-ux** [comment]
![Screen Shot 2022-09-20 at 12.30.34 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/ce89aaf0-baa5-435b-925d-76eb9c199a6e)

**Comment by elisafw-ux** [comment]
There's only one place in the portal that allows a user to enable an environment, and that is in: products > edit env > configure env 

which will be greyed out if an Organization is not assigned to a namespace yet as seen on the screenshot above.
