### ISSUE TITLE
Namespace Access

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#592]
1. As a user I want to be able to edit access if:

a. I want to add or remove permission
b. I typed the wrong username and I want to change it

2. As a user I want to know what each of the permissions mean w/o needing to refer to documentation so that I can quickly make a decision.

Designs

**1. Edit Access**

![Screen Shot 2022-10-06 at 9.31.47 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/abf4204d-f4a5-486a-9c9f-f9c50b2c5dfa)

**2. Permissions**
Add definitions on Grant User Access, Grant Service Account Access, Create New Service Account, Edit Access

![Screen Shot 2022-10-06 at 9.32.26 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/864c0855-52f1-4817-9f89-5ae96ce8ba85)

**Comment by elisafw-ux** [comment]
Notes: 

regarding "Namespace.View" - atm viewing Consumers, Auth Profiles and Namespace Access are excluded from this permission.. we should probably decide whether it should be all or whether a new permission is needed or keep as is..

**Comment by ikethecoder** [comment]
@Jonesy Backend changes are complete.

Use branch `feature/ns-access-ui` as the other one was too long and causing issues during deployment.

There are now `grantPermissions` and `updatePermissions` - they share the same structure, but `grantPermissions` will fail if permission already exist.

There are also `createUmaPolicy` and `updateUmaPolicy` for the service accounts.

**Comment by Jonesy** [comment]
I think I got all of the requests updated in the whitelist @ikethecoder , we just need to figure out where to store the help text under each permission checkbox. Also is all the content for each possible permission saved somewhere I can copy from @elisafw-ux ?
