### ISSUE TITLE
Access can be granted to Inactive environment also.

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#632]
Step 1: Click on Grant Access button from Consumer Page
Step 2: Select a Product that has Active as well Inactive Environments
Step 3: In environment Drop Down, select the Inactive Environment
Step 4: Click on Grant Access Button

Actual Result : Access can be granted to Inactive environment also.

Expected Result : Inactive Environment should not be displayed in Environment Drop Down to prevent access for Inactive Environment

**Comment by rustyjux** [comment]
@Elson9 was the change implemented in #825 not a complete solution to this issue?

**Comment by Elson9** [comment]
@rustyjux it was a complete solution. This issue can be closed.
