### ISSUE TITLE
Not able to find dataset when searching on the Product Edit dialog

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#651]
# API Services Portal Issue

## User Story

**As a** API Provider,<br>
**I want** to associate a Dataset to a Product<br>
**so that** I can publish it on the API Directory.

### ENV

- [ ] `DEV`
- [ ] `TEST`
- [X] `PROD`

### TESTCASE

- Create a dataset with a title of "My Test Dataset"
- Create a Product
- Go to Edit Product and enter "My Test" on the Link to BC Data Catalog field

### EXPECTED

- The "My Test Dataset" should appear

### ACTUAL

- No records appear

**Comment by ikethecoder** [comment]
I believe the cause is that the `allDatasets` GraphQL query is using `search: $value` but it probably should be using `where: { title_contains: $value }`.

It may also be related to the fact that we include `first: 25`.  If the search is happening after getting the first 25, then it will not be searching the full set of records.

**Comment by elisafw-ux** [comment]
This ticket can remain as Done. 

Created a new ticket w/r to the empty state when no dataset is found. See [693](https://app.zenhub.com/workspaces/bc-gov-api-services-60943b8bf73eb300102d9c97/issues/gh/bcgov/api-services-portal/693).
