### ISSUE TITLE
Delete Consumer option does not work

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#664]
Step 1: Sign in as API Owner
Step 2: Select the Consumer that is associated to more than one product environment
Step 3: Select the meatball icon and click on Delete Credential

Actual Result : System displays 'Consumer delete failed' error message

Expected Result : Delete Consumer option should delete the selected Consumer

![image.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/3bfff847-2837-4421-9f55-fe96cbcf0613)

aps-log
apsportal                                 | warn: [authz] {"gqlName":"revokeAllConsumerAccess","item":{},"user":{"tid":"10","id":"7","roles":["api-owner","credential-admin","portal-user","idir-user"],"scopes":"[\"Namespace.Manage\",\"CredentialIssuer.Admin\"]","namespace":"newplatform"}}
apsportal                                 | {"level":30,"time":1670893525523,"pid":25,"hostname":"4b2101f81c4c","name":"graphql","gqlName":"revokeAllConsumerAccess","msg":"Access Denied"}
apsportal                                 | error: [general] GraphQL Error: You do not have access to this resource
apsportal                                 |
apsportal                                 | GraphQL request:3:5
apsportal                                 | 2 |   mutation RevokeAllConsumerAccess($id: ID!) {
apsportal                                 | 3 |     revokeAllConsumerAccess(consumerId: $id)
apsportal                                 |   |     ^
apsportal                                 | 4 |   }
apsportal                                 | {"level":30,"time":1670893525526,"pid":25,"hostname":"4b2101f81c4c","name":"graphql","type":"error","data":{"type":"mutation","target":"revokeAllConsumerAccess"},"internalData":{"authedId":"10","authedListKey":"TemporaryIdentity"}}
oauth2-proxy                              | 172.18.0.1:55810 - 04be7af5-99cf-4a13-8ef5-e77b3b63dba2 - janis@testmail.com [2022/12/13 01:05:25] oauth2proxy.localtest.me:4180 POST / "/gql/api" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 200 306 0.024
apsportal                                 | {"level":30,"time":1670893525529,"pid":25,"hostname":"4b2101f81c4c","req":{"id":1284,"method":"POST","url":"/gql/api","headers":{"host":"oauth2proxy.localtest.me:4180","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","content-length":"136","accept":"application/json","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9","content-type":"application/json","cookie":"_oauth2_proxy=X29hdXRoMl9wcm94eS04MjI1NGI4MDI2YjE2N2I3MGQ2YzJkMmZjNjdmYjg1MC5VV1dtNFlMZlZiWlRpNGxYV3p4TGR3|1670893509|mnYg5eqZwvSWYsWoQSxx8FMy3OomMLGZXypVY5ctuKI=; keystone.sid=s%3AxK-tJu6hg9j9_j9V9wxYNIkSVBkLSNVJ.UrWCWQ5uqpchKNXwN6kUJn%2BDL5QxBWHf3YfRZBP5zRk","origin":"http://oauth2proxy.localtest.me:4180","referer":"http://oauth2proxy.localtest.me:4180/manager/consumers","x-forwarded-access-token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4bWxJbUplOXhxUFphMlNEYVlGMTBLWjJjUUhKQ2t0OEN1TjhNYjd5YkhVIn0.eyJleHAiOjE2NzA4OTM4MDksImlhdCI6MTY3MDg5MzUwOSwiYXV0aF90aW1lIjoxNjcwODkzNTA5LCJqdGkiOiI0MDgyYjRmZC05Y2U1LTQ0ODUtOGIyOC0yZGMzMGU4Yjg3MzYiLCJpc3MiOiJodHRwOi8va2V5Y2xvYWsubG9jYWx0ZXN0Lm1lOjkwODAvYXV0aC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiYmY0OThhN2ItYjZlMC00OWJiLTllYTgtMDI0MWQ3NzkyZmUyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYXBzLXBvcnRhbCIsInNlc3Npb25fc3RhdGUiOiJjYjFjMmY4ZC0zOTRhLTRlNTctODAxMC04OTVhMGU2OGM3MmYiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJvcGVuaWQgTmFtZXNwYWNlLkFkbWluIGVtYWlsIHByb2ZpbGUgTmFtZXNwYWNlLkNyZWF0ZSIsImlkZW50aXR5X3Byb3ZpZGVyIjoiaWRpciIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJvdmlkZXJfdXNlcm5hbWUiOiJqYW5pcyIsIm5hbWUiOiJKYW5pcyBTbWl0aCIsInByb3ZpZGVyX3VzZXJfZ3VpZCI6IjIyMDQ2OUUwMzdDODRBN0FCREZBQjE1MjA0QTYwN0M1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiamFuaXNAaWRpciIsImRpc3BsYXlfbmFtZSI6IkphbmlzQGlkaXIiLCJnaXZlbl9uYW1lIjoiSmFuaXMiLCJmYW1pbHlfbmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqYW5pc0B0ZXN0bWFpbC5jb20ifQ.Gyomj9tLEp6Bde_DpUqMwhFJuU9jHMYO3fpW-BTXWWF91lFNRfs6KIrs5aWO-WSbkRJLuWqfPdI3PgSOpR9EBG6HW9IV57sm6unFJxSGWVR8p5Qs8TsA7YtltvvrRix2r0NQhtbvmF_5c1h98Tr85XPO9E3jEBut63oPW3ce90sGzsknY_di_jSj4XJZOgb9e5Oyf985ClJ0tJ7u952rzUOr_1tVaiH0NQK6HKLfj700WhnSj-1NFP35APytJRDqDVRSstY0pz5iwEu9vnTlezHEjLUZHlb5vslT2qjGf0SGPfhsHOpexVJ5jeQhd3rFb_XK7_igUS7PeYWZVPMMDQ","x-forwarded-email":"janis@testmail.com","x-forwarded-for":"172.18.0.1","x-forwarded-preferred-username":"janis@idir","x-forwarded-user":"bf498a7b-b6e0-49bb-9ea8-0241d7792fe2"},"remoteAddress":"::ffff:172.18.0.6","remotePort":54068},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","x-keystone-app-version":"1.0.0","access-control-allow-origin":"http://oauth2proxy.localtest.me:4180","vary":"Origin","access-control-allow-credentials":"true","content-type":"application/json; charset=utf-8","content-length":"306","etag":"W/\"132-XmtJhgi7dv69uOY2pJnddFxnP5A\""}},"responseTime":12,"msg":"request completed"}
oauth2-proxy                              | 172.18.0.1:55810 - 930e9b6d-d36f-458d-a80f-9f7674358712 - janis@testmail.com [2022/12/13 01:05:37] oauth2proxy.localtest.me:4180 GET / "/admin/session" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 304 0 0.020

**Comment by chrsamp** [comment]
@Elson9 @jTendeck another one to repro :-)

**Comment by Elson9** [comment]
Met with Niraj yesterday to investigate. Found that issue occurs in some situations but not others. Will discuss and look into more at knowledge sharing session.

**Comment by ikethecoder** [comment]
The error in the description is "You do not have access to this resource" - which indicates the user does not have the "Access.Manage" permission.  Did you try this with a user that has that permission?

**Comment by Elson9** [comment]
Opting to display a more descriptive error message. There are 2 scenarios we have discovered:
- User does not have 'Access.Manage" permission, where we will display: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVhkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a011b593572fb8ff340c0c860eca3bcb267d57f/image.png)
- Consumer has access to multiple products or multiple environments, where we will display: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTNkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3624ee51496414749c7519911747b119203909be/image.png)

**Comment by nirajCITZ** [comment]
As per @ikethecoder , consumer is not allowed to delete if it is associated with more than one product environment, so this behaviour is as expected. However, system displays message `Consumer delete failed` rather than proper message like can not be deleted due to multiple product environment
