### ISSUE TITLE
New login page UI fixes (in test)

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#674]
Linked to [643](https://app.zenhub.com/workspaces/bc-gov-api-services-60943b8bf73eb300102d9c97/issues/gh/bcgov/api-services-portal/643)

**Issue 1:** Login for the Developers. The order should be:

Option 1: Login with your IDIR
Option 2: Login with your BCSC
Option 3: Login with BCeID
Option 4: Login with Github

**Issue 2:** When a user lands on the homepage, the "For API Providers" link should go to the new login for API Providers. Right now it does here: 

![Screen Shot 2023-01-02 at 1.10.42 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/81f29114-06fd-452d-a785-0ab084e026b5)

**Comment by Jonesy** [comment]
@ikethecoder I fixed issue 2, just need you to change the order of the developer identities in the `NEXT_PUBLIC_DEVELOPER_IDS` when you have a chance. Thanks!
