### ISSUE TITLE
Update Cypress Version from 9.3.0 to 12.0.1

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#711]
- [x] Update Cypress Project as per below migration guide for version 12.0
https://docs.cypress.io/guides/references/migration-guide

- [x] Update Cookies.preserveOnce() function as it is been deprecated in version 12.0

- [ ] Run existing cypress tests to verify their compatibility for latest version

**Comment by JohnathanBrammall** [comment]
Current version 12.4.0 is now active in APS' test suite. Closing ticket.
