### ISSUE TITLE
Improve the UX of revoking access and deleting consumer

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#715]
A consumer receives a unique client id and client credentials are created when the consumer requests access to a product and an environment. The expectations is that when an API provider revokes access to a product/environment, and no products remain attached to that consumer, it automatically deletes the consumer.

Current issues: 
- There's a potential bug when a user revokes product access, the system throws a success toast when it should've been a fail. (not able to immediately reproduce)

Acceptance criteria:
- We are able to reproduce the bug
- We have triaged the ticket as something that we want to fix in a future release
- We have documented whether we want the credentials to be deleted from the IdP at the same time

**Comment by odyeung** [comment]
related to ticket 880. please look at that before addressing this issue!

**Comment by ikethecoder** [comment]
The user will now get an error:
<img width="586" alt="image" src="https://github.com/bcgov/api-services-portal/assets/23747270/2779a04f-6326-425c-b8f6-fdec956d8e4b">
