### ISSUE TITLE
null Users

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#717]
As a user who logged in using Github, I don't want to be referred as `null` on the emails. 

As an api provider looking at the activity feed, any other information other than user = `null` could be more helpful. 

DoD: find alternatives to replace `null`

**Comment by ikethecoder** [comment]
@elisafw-ux in Github, the `name` is actually optional, which is the reason I think that some Github users get that `null` reference related to access requests.  I think the fix (specifically for Github logins) would be to use the `username` in the event that the `name` is not provided.  Do you agree?


![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/e10e921a-48f5-4a7b-8ab7-75d443ae3876)

**Comment by elisafw-ux** [comment]
@ikethecoder Agreed, I was thinking exactly the same, using the Github username when the name is nor provided.
