### ISSUE TITLE
Add confirmation modal to Delete Application

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#740]
- Implement a confirmation modal to prevent deleting an application accidentally. 
- Add an ellipsis (...) to the action to indicate there's a step further "Delete Application..."

Outstanding question for microcopy: 

~- What is the outcome of the deletion?~ Done 

[Design](https://www.figma.com/file/00SZt0Ezx1DGz1x1tlcNLL/APS-Portal-Designs?node-id=29022%3A15694&t=C6w0y1QtzfuSjdjX-1)

**Comment by ikethecoder** [comment]
Deleting an application will delete all related credentials found under My Access.
