### ISSUE TITLE
feat: manage individual services via console UI

### ISSUE THREAD

**Issue by ll911** [bcgov/api-services-portal#775]
# API Services Portal Issue

Unable to delete single service.

## User Story

**As a** _ API provider_,<br>
**I want** _ to mange individual services under the same namespace_<br>
**so that** _other running services not impacted_.

| **As A**      | **I Want**    | **So that**  |
| ------------- | ------------- | ------------ |
| _< API provider >_ | _< to mange individual services under the same namespace >_ | _< other running services not impacted >_ |

### ENV

- [ ] `DEV`
- [ ] `TEST`
- [ x ] `PROD`

### TESTCASE

-

### EXPECTED

-

### ACTUAL

-

**Comment by ikethecoder** [comment]
Leo, the declarative configuration that you create for the gateway is expecting the "desired state" and then Kong's DecK utility (https://docs.konghq.com/deck/latest/) figures out the changes needed to bring Kong to that desired state.  So to delete a service, you only need to remove the service from your configuration files and re-run `gwa pg`.  That should result in the service being removed from the Kong Gateway.
