### ISSUE TITLE
Wrong URL for release notes in Help menu

### ISSUE THREAD

**Issue by chrsamp** [bcgov/api-services-portal#785]
# API Services Portal Issue

## User Story

**As a** _developer_,<br>
**I want** _to read the latest release notes_<br>
**so that** _I can understand how a release will impact me_.

### ENV

- [ ] `DEV`
- [x] `TEST`
- [x] `PROD`

### TESTCASE

1. Browse to api.gov.bc.ca
2. Open the 'Help' dropdown menu in the header nav
3. Click 'Release notes'

### EXPECTED

- Browser should navigate to https://bcgov.github.io/aps-infra-platform/releases/2023-mar-1.2.11/

### ACTUAL

- Browser navigates to https://bcgov.github.io/aps-infra-platform/releases/2022-may/

**Comment by ikethecoder** [comment]
Since we probably don't want to keep updating the link in the Portal, perhaps we just have it got here:
https://bcgov.github.io/aps-infra-platform/releases/

@elisafw-ux

**Comment by elisafw-ux** [comment]
Yes please!

**Comment by ikethecoder** [comment]
@Jonesy A miscellaneous UI fix when you have a minute :)
