### ISSUE TITLE
Improve namespace name uniqueness in Create a Namespace modal

### ISSUE THREAD

**Issue by elisafw-ux** [bcgov/api-services-portal#806]
The requirement is that a namespace name must be unique to other namespaces in the APS Portal. 

During a usability session, it was observed that when an api provider inputs a common namespace name, the system gave a validation error indicating that the name has already been used. Api providers may not know what names have already been used in other people's namespaces, and this can may cause confusion and frustration.

The system will not give an error if the user has thought of a unique name but in instances where users just want to use a very common name such as “test”, then it will most certainly give an error.  

How can we use the content in this [doc](https://bcgov.sharepoint.com/:w:/r/teams/00108/Shared%20Documents/TM_APS/APS%20Documentation/Client-facing%20Documentation/Common%20Patterns/Common%20Namespace%20Patterns.docx?d=wd059bf8abd784a0ea967b0140c900d72&csf=1&web=1&e=AdJLKc) to improve the messaging around creating a new namespace so that it prevents throwing an error? 

**Steps to reproduce**
1. Log into https://api-gov-bc-ca.test.api.gov.bc.ca/ as an api provider
2. Click on the "no active namespaces" dropdown located on the top right
3. Click on Create a Namespace

**Comment by chrsamp** [comment]
This is also relevant for namespace naming requirements (i.e. can't start with a number, end with a hyphen). Currently the API returns a generic error message, this would benefit greatly from being more specific and helpful for users.

**Comment by nathaliamorales** [comment]
We are proposing 'Namespaces names' to be created automatically with an alphanumeric id (similar to open shift's licence plates). A new design was proposed and we are currently testing with users the replacement of namespaces for gateways. This issue moved to Jira and multiple tickets had been created. The last ticket so far is [analyze findings from gateways user testing - 1828](https://dpdd.atlassian.net/browse/APS-1828?atlOrigin=eyJpIjoiZTU4ZmU0NDUwNTA4NDJkMzg5YmE5M2MwYmZhNTEwY2IiLCJwIjoiaiJ9 )

**Comment by nathaliamorales** [comment]
We are proposing 'Namespaces names' to be created automatically with an alphanumeric id (similar to open shift's licence plates). A new design was proposed and we are currently testing with users the replacement of namespaces for gateways. This issue moved to Jira and multiple tickets had been created. The last ticket so far is [analyze findings from gateways user testing - 1828](https://dpdd.atlassian.net/browse/APS-1828?atlOrigin=eyJpIjoiZTU4ZmU0NDUwNTA4NDJkMzg5YmE5M2MwYmZhNTEwY2IiLCJwIjoiaiJ9 )
