### ISSUE TITLE
Consumers appearing twice

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#843]
# API Services Portal Issue

## User Story

**As an** Access Manager,<br>
**I want** to be able to filter a list of consumers, find a consumer and get detail on a consumer's access to a product<br>
**so that** I can manage access effectively .

### ENV

- [ ] `DEV`
- [ ] `TEST`
- [X] `PROD`

### TESTCASE

- Go to a namespace that has a user consumer accessing two different products
- Go to Consumer list and filter by one of the Products

### EXPECTED

- A single row for that particular user

### ACTUAL

- Two rows with duplicate information

## Notes

**Additional Scope of Change**

* From the consumer detail, clicking on the Product Edit brings up the dialog but fails to retrieve details.
* The Service Accounts list is showing Consumer records for legacy “client” consumers

**Comment by Elson9** [comment]
A couple examples: dbcols, blueinc.
Alix is concerned that some people have access that shouldn't.
Sort by name not working properly.

**Comment by ikethecoder** [comment]
Recreating the issue in Test - using `moh-proto` namespace:

Consumer: After requesting access to the Pharmanet API, I received a new consumer "535C4DF2-070C92957B1".  Then took that consumer and manually created a new "ServiceAccess" record in postgres to replicate a production migration of legacy consumers.

```
keystonejs=# insert into "ServiceAccess" (name, namespace, consumer, application, "productEnvironment", active, "aclEnabled", "consumerType") values ('535C4DF2-070C92957B1 for sandbox', 'moh-proto', 16885, 401, 428, false, false, 'client');
INSERT 0 1
keystonejs=# select * from "ServiceAccess" where name = '535C4DF2-070C92957B1 for sandbox';
keystonejs=# update "ServiceAccess" set "updatedAt_utc" = '2023-09-21 22:35:41.667', "createdAt_utc" = '2023-09-21 22:35:41.667', "updatedAt_offset" = '+00:00', "createdAt_offset" = '+00:00' where id = 1050;
UPDATE 1
```

As a result of adding another "ServiceAccess" record for the particular consumer, two records now appear on the Consumers page.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkRHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3265c07a1f7fdc83d7c00c8305f32319c1223d5a/image.png)

**Comment by Elson9** [comment]
Steps to reproduce:
- Create a product
- Enable dev environment and require approval
- Request access to product and approve
- Perform similar database modifications as Aidan mentioned above, with name, namespace, consumer, application, and productEnvironment modified to match local portal instance

Connecting to Docker database:
`docker exec -it kong-db psql -U postgres -W postgres`
`\c keystonejs`
