### ISSUE TITLE
Namespaces to Gateways Redesign

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#852]
## Change Terminology: Namespaces to Gateways

**Technical Scope**

It will not be practical to replace all code and database references from "namespace" to "gateway", so a pragmatic approach will be taken:

* Database structure for Portal will remain the same
* Portal Lists will remain the same
* A `v3` of the Directory API and Gateway API will be created that refers to "gateways" rather than "namespaces" and Entities will be aliased to Gateways.
* Do not believe there are GraphQL references to namespace as it is typically injected into the GQL by the Authorization matrix, so no changes expected for these
* Update portal labeling to use "Gateway(s)" instead of "Namespace(s)"
* Update aps-infra-platform public documentation for re-labeling
* Re-labeling of client facing Grafana dashboards
* Depends on the new version of the `gwa-cli`.

Changes in Cypress Automation Tests:

- Update existing UI flows to create namespace through gwa-cli
- Update APS API tests for directory and gateway end points
- Update UI tests to use "Gateway(s)" instead of "Namespace(s)"

**Comment by odyeung** [comment]
niraj is looking over this! what are the technical and scope of the gateway redesign. what the changes are expected etc
