### ISSUE TITLE
Publish Gateway with Select Tag Qualifier

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#862]
For `publish-gateway`, there should be a `--select-tag-qualifier <qualifier>` that can be used to specify that the gateway configuration is a partial set of configuration.  It will get passed to the `gwa-api`.

The typical scenario where this can be useful is when there is no config and you want to specify exactly which select tag will be used.

The select tag is derived from `ns.<namespace>.<qualifier>`.

**Comment by ikethecoder** [comment]
Yeah, it would just be another parameter "qualifier" that is passed with dryRun and configFile.  It's an optional parameter too - does not have to be sent.

**Comment by nirajCITZ** [comment]
HI @ikethecoder  - Can you please suggest what qualifier or changes should I do in my below config file to test   --qualifier tag in gwa pg command?

services:
- name: a-service-for-newplatform
  host: httpbin.org
  tags: [ns.newplatform]
  port: 443
  protocol: https
  retries: 0
  routes:
  - name: a-service-for-newplatform-route
    tags: [ns.newplatform.dev]
    hosts:
      - a-service-for-newplatform.api.gov.bc.ca
    paths:
      - /
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    
- name: a-service-for-newplatform-test
  host: httpbin.org
  tags: [ns.newplatform]
  port: 443
  protocol: https
  retries: 0
  routes:
  - name: a-service-for-newplatform-test-route
    tags: [ns.newplatform]
    hosts:
      - a-service-for-newplatform-test.api.gov.bc.ca
    paths:
      - /
    methods:
      - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0

**Comment by ikethecoder** [comment]
Your config still needs the namespace details and to add a qualifier (like 'dev' for example) it would become: `tags: [ ns.platform.dev ]`.

But, the backend `gwa-api` does not support the extra qualifier parameter yet.. so that's why it is not behaving the way that you expect.

**Comment by ikethecoder** [comment]
`gwa-api` https://github.com/bcgov/gwa-api/releases/tag/v1.0.28 now has this feature.
