### ISSUE TITLE
Cypress test for GWA generate-config and apply command

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#868]
1. Verify CLI commands for generate/apply config
1.1 authenticates Janis (api owner) to get the user session token
1.2 Check gwa config command to set token
1.3 Check gwa command to generate config for client credential template
1.4 Check gwa command to apply generated config
1.5 Check gwa command to generate config for kong httpbin template
1.6 activates new namespace
1.7 Verify that the product created through gwa command is displayed in portal
1.8 Verify the Authorization scope and issuer details for the product

**Comment by nirajCITZ** [comment]
@ikethecoder - Should Organization and Organization value should be derived from user inpul (i.e praramirized these values through command) instead of static values while generating config file  using 'gwa generate-config' command? 

![image.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/c0d99841-cd8e-4431-b88d-1e40f4b1455a)

**Comment by odyeung** [comment]
@ikethecoder bump!!

**Comment by nirajCITZ** [comment]
Shared authorization profile created in one namespace can be inherited from another namespace if:
1)isShared set as true for the shared auth profile
2)perm-protected-ns set as 'allowed' for the namespace where shared profile is created

**Comment by nirajCITZ** [comment]
Scenarios for client credential template is completed and working on kong-httpbin template but getting following error for this template
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakloIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d3e9daa3dc36d13fd6dcafbd51987fb93d2fb12/MicrosoftTeams-image.png)

Informed to @Jonesy about this behaviour and he is looking into it

**Comment by nirajCITZ** [comment]
As per discussion with @ikethecoder and @Jonesy , 'gwa apply' command would not be applicable for kong-httpbin template. The command would generate the gw-config.yml file and user can use 'pg publish'to publish it to kong
