### ISSUE TITLE
Update Cypress Test for access-permission, delete application, namespace-preview, org assignment and aps-api specs

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#869]
- [x] Update reference of test data file to fetch new namespace details
- [x] Update steps to publish config file to Kong
- [x] Update namespace in the APS v2 API end points
- [x] Update service/host name to make call to the published APIs
- [x] Add step to upload issuer using 'gwa publish issuer'command

**Comment by odyeung** [comment]
apply config command -- and was blocked. with APS switch over branch -- now unblocked

**Comment by odyeung** [comment]
@ikethecoder add notes here
