### ISSUE TITLE
GWA generate config - Give user an option to set 'Organization Name' and Organization Unit' values in the 'gw-config.yaml' file generated by 'gwa generate config'command

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#870]
Organization and Organization value should be derived from user inpul (i.e praramirized these values through command) instead of static values while generating config file using 'gwa generate-config' command

![image.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/c0d99841-cd8e-4431-b88d-1e40f4b1455a)

**Comment by nirajCITZ** [comment]
Hi @Jonesy - Could you please take a look into this issue whenever you get time

**Comment by Jonesy** [comment]
Users can set `--org` and `--org-unit` now when running this command

**Comment by nirajCITZ** [comment]
Verified and working fine
