### ISSUE TITLE
Cypress Test to verify 'gwa namespace destroy' command

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#871]
- [x] Design Test Cases/scenarios  of  GWA namespace destroy
- [x] Prepare Test Script around the scenarios
- [x] Execute the scenarios to make sure all are working fine

1. Verify namespace delete using gwa command
1.1 authenticates Janis (api owner) to get the user session token
1.2 set token using gwa config command
1.3 create namespace using gwa cli command
1.4 Check gwa namespace destroy command for soft deleting namespace
1.5 Check that deleted namespace does not display in gwa namespace list command
1.6 Check gwa namespace destroy command for the namespace associated with services
1.7 Check gwa namespace destroy command for hard deleting namespace
1.8 Check that deleted namespace does not display in gwa namespace list command

**Comment by odyeung** [comment]
there is some confluence page that @Jonesy will be updating with regards to the GWA as per @nirajCITZ

**Comment by odyeung** [comment]
@Jonesy are you able to add the link to the confluence page here?
