### ISSUE TITLE
namespace create does not work to create new namespace based on user's own name

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#872]
Step 1: Create namespace with the user's own name using following gwa command
gwa namespace create -n <name>

Step 2: Verify that the namespace is created with given name

Actual Result : gwa creates auto generated name for the command to create namespace with user's own name

Expected Result : gwa should create namespace with the name given by user to generate his own name for namespace

**Comment by Jonesy** [comment]
Pushed a fix for this @nirajCITZ

**Comment by nirajCITZ** [comment]
Verified and working fine
