### ISSUE TITLE
Cypress Test for `gwa get`

### ISSUE THREAD

**Issue by Jonesy** [bcgov/api-services-portal#873]
New command has been added, `gwa get [operator]`, which retrieves a list of datasets, products or issuers from the API.

Example usage
```shell
$ gwa get datasets
$ gwa get datasets --json
$ gwa get datasets --yaml
$ gwa get issuers
$ gwa get products
```

The `--json` or `--yaml` return the selected format as string, so the user can pipe them to another function like writing to a file.

1. Verify GWA get commands
1.1 authenticates Janis (api owner) to get the user session token
1.2 Check gwa config command to set token
1.3 Verify "gwa get" for dataset
1.4 Verify "gwa get" for dataset in JSON format
1.5 Verify "gwa get" for dataset in YAML format
1.6 Verify "gwa get" for products
1.7 Verify "gwa get" for issuers

**Comment by nirajCITZ** [comment]
Hi @Jonesy  - Getting error with latest code in 'dev' branch while performing 'just build' to build CLI executable binary file. Could you please look into it?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTBCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c807fbaf66b99c5352795ba34a500756543959e2/image.png)

**Comment by Jonesy** [comment]
Just pushed the fix, let me know if you still get any issues @nirajCITZ

**Comment by Jonesy** [comment]
@nirajCITZ added `gwa get organizations` to the list of possible `get` operations

**Comment by nirajCITZ** [comment]
Forgot to dd verification step for 'Verify "gwa get" for issuers'
