### ISSUE TITLE
Hard delete ( force delete) cause namespace list service fails and does not display namespaces in the drop down

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#876]
Preconditions : 
1) Have a namespace associated with multiple services and service account
2) More than one namespaces displays in the drop down list

Step 1 : Perform hard delete (force delete) using gwa command or through API to delete the namespace associated with multiple services or service accounts
Step 2: Verify that drop down list does not displays the deleted namespace but displays the remaining namespaces in the list

Actual Result : Hard delete ( force delete) cause namespace list service fails and does not display namespaces in the drop down

Expected Result : Hard delete ( force delete) should not cause namespace list service fail and should display namespaces in the drop down

Environment  : Local docker

**Comment by nirajCITZ** [comment]
Hi @ikethecoder - Could you please check if this issue also persists in dev or hight environment as I do not have sufficient permissions to check this behaviour in other than local docker environment?

**Comment by chrsamp** [comment]
@Elson9 @jTendeck Suggesting one of you try to repro this

**Comment by JohnathanBrammall** [comment]
This issue needs to be confirmed as still affecting the service with the new version of the CLI in production.

**Comment by ikethecoder** [comment]
Have made some updates to handle the namespace deletion cleaner. Also changed the cascading logic so that if there are consumers, it will stop you from deleting the namespace even with the force=true option. Consumers will need to be cleaned up (revoked) before the namespace can be deleted.  Related to #459
