### ISSUE TITLE
Confirm when deleting resources

### ISSUE THREAD

**Issue by chrsamp** [bcgov/api-services-portal#880]
As an API provider, I want to have a confirmation modal appear when making destructive actions, so that I do not accidentally revoke access to the wrong entity.

All the places that there is a deletion:

| Page                                     | Action                             | Confirmation dialog implemented | Updates Needed? |
| ---------------------------------------- | ---------------------------------- | ------------------------------- | --------------- |
| My Access                                | "Revoke Access" menu item          | NO                              | -      |
| Applications                             | "Delete Application..." menu item  | YES                             | -               |
| Namespaces                               | "Delete Namespace..." button       | YES                             | -               |
| Namespaces / Products                    | "Delete Product..." menu item      | YES                             | -               |
| Namespaces / Products                    | "Delete Environment..." menu item  | YES                             | -               |
| Namespaces / Authorization Profiles      | "Delete" menu item                 | NO                              | Add Dialog      |
| Namespaces / Namespace Access            | "Revoke Access" menu item          | NO                              | -               |
| Namespaces / Service Accounts            | "Delete Service Account" menu item | YES                             | -               |
| Namespaces / Consumers / Consumer Dialog | "Revoke Access" menu item          | NO                              | -               |
| Namespaces / Consumers                   | "Delete Consumer" menu item        | NO                              | Add Dialog      |
 
Acceptance criteria:
- New confirmation dialog on the Authorization Profiles delete menu item
- New confirmation dialog on the Delete Consumers menu item

**Comment by odyeung** [comment]
is this still relevant?

**Comment by odyeung** [comment]
check behavior of when user deletes consumer cc @nirajCITZ

**Comment by ikethecoder** [comment]
**Authorization Profile:**
```
Title: "Delete ${c.name} Authorization Profile?"
Notice: This action cannot be undone
Button: Yes, Delete
```

**Consumer:**
```
Title: "Delete ${d.username} Consumer?"
Notice: This action cannot be undone
Button: Yes, Delete
```
