### ISSUE TITLE
Upgrade Cypress version from 12.4.0 to 13.2.0 and make sure current tests are compatible with latest version

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#915]

**Comment by odyeung** [comment]
make sure you include @Elson9 @jTendeck

**Comment by odyeung** [comment]
make sure you include @Elson9 @jTendeck

**Comment by nirajCITZ** [comment]
In the latest Cypress version 13.2.0, the OAuth callback is not handled properly. The session is not maintained correctly, leading to the home page not loading and causing the test to fail.

This issue only occurs when the spec contains multiple test scenarios. A single scenario in a spec file works fine.
