### ISSUE TITLE
'Service Account' section description is inaccurate

### ISSUE THREAD

**Issue by nathaliamorales** [bcgov/api-services-portal#935]
Context:

While reviewing the Service Account section, Aidan noticed that the section description is incorrect. 

It should say: “ Service Accounts allow you to administer your gateway”

Instead of: “Service Accounts allow you to access BC Government APIs via the Gateway API or the Gateway CLI”

Definition of done:

When the new description is accepted and published to test and production.

**Comment by ikethecoder** [comment]
New content added:
<img width="937" alt="image" src="https://github.com/bcgov/api-services-portal/assets/23747270/4dbd98aa-599a-4166-b8a1-7bf49805c5c9">
