### ISSUE TITLE
Enabling API publishing toggle button:  Label and description change

### ISSUE THREAD

**Issue by nathaliamorales** [bcgov/api-services-portal#936]
Context: 

1. To be able to publish their APIs in the API directory, providers need to associate their products to an organization (government ministry). When providers assign an organization to their products, the Org. admin user receives the request, and they will see an option to approve it. Once approved, they will see a toggle button (in a off state) which allows the requester to publish their APIs. If the org. admin user does not turn it of, the provider will get an error message if they try to publish their API. Once the org admin user turns the toggle on, the provider will see that their product state changes to active and will be able to publish their API by editing their product, and selecting the checkbox option “enable environment”

2.while reviewing a Namespace product page as an org. admin user, I noticed the Enabling API toggle button indicated “publishing APIs”. Discussing with Aidan about what this toggle button does, he explained that the button will not publish any API,  it will grant permission to the providers user to publish their APIs. This means that the toggle's action is not publishing, is granting permission. Although it was reviewed in the past and no action was taken at that moment, I must suggest to change the label and description to reflect the exact immediate action that the user triggering the toggle (org admin) will do: grant permission. 

3. According to Norman Nielsen Group and their Toggle-switch guidelines “The toggle labels should describe what the control will do when the switch is on; they should not be neutral or ambiguous.” This means that the toggle label should be say explicitly and concisely what the result of turning it on will be. If we analyze the label “publishing APIs”, it mistakenly indicates that by turning it on, the org admin will publish an API. When the person who will publish the API, is a different user (not the org admin that clicks the toggle), a different profile ( a provider), at a different moment (later after the org admin grants the permission to do so). The toggle label should indicate the action that the user triggering it is doing, not the action that other user will do in a different moment using a different button.

 

My suggestion:

- Label: indicate exactly the immediate action what the control will do. The label for the button could be “grant permission to publish API”

- Description: indicate the next consequence: Providers being able to publish, which leads to the next consequence: Consumers being able to access the APIs in the directory. The description could  be “Allow providers to publish their products to the API directory so they can make their APIs discoverable to consumers.”

## User Story

**As a** Organization Admin,<br>
**I want** to understand what the "Enable API" toggle button does<br>
**so that** I can make a clear decision about whether I should enable it or not.

### ENV

- [X] `DEV`
- [X] `TEST`
- [X] `PROD`

### TESTCASE

- Log in with a user that has the Org Admin role
- Select a namespace that has an org assigned
- Go to Products

### EXPECTED

- The toggle button to have "Grant permission to publish APIs" 

### ACTUAL

- The toggle button says "Publish APIs"

**Comment by ikethecoder** [comment]
Updated content:
<img width="1204" alt="image" src="https://github.com/bcgov/api-services-portal/assets/23747270/dc85c559-fa06-4326-be42-f7dc9f55c2ae">
