### ISSUE TITLE
Product is not created with gwa apply command

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#946]
Step 1: Generate config file with following command
gwa generate-config --template client-credentials-shared-idp --service my-service --upstream https://httpbin.org --org ministry-of-health --org-unit planning-and-innovation-division

Step 2 :  Apply 'gwa apply' to publish gateway service, credential issuer, dataset and  product define in gw-config.yml file

Actual Result : Product is not created with gwa apply command, gateway service, credential issuer, dataset are published successfully. However, product is also published with second attempt

Expected Result : All the entities in gw-config.yml file should be created successfully in first attempt

Environment: local
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemlHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f02b3205211e3510791f4138c6313520b888505d/Screenshot%202023-10-30%20at%204.41.15%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1HQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aeae11c5f6b959a1e5207c01c258a724de1fb20b/Screenshot%202023-10-30%20at%204.37.24%20PM.png)

**Comment by ikethecoder** [comment]
This is happening because the CLI is processing `GatewayService` resources last - which is causing the Environment to fail creation because it can't find the referenced `service`.  Suggest that the CLI should process GatewayService resources first. cc/ @Jonesy
