### ISSUE TITLE
Kong 3.x : System displays schema violation error while applying config file to Kong

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#960]
For below config file, system displays schema violation error while uploading the file

services:
    -
        name: cc-service-for-platform
        host: httpbin.org
        tags:
            - ns.gw-b8244
        port: 443
        protocol: https
        retries: 0
        routes:
            -
                name: cc-service-for-platform-route
                tags:
                    - ns.gw-b8244
                hosts:
                    - cc-service-for-platform.api.gov.bc.ca
                paths:
                    - /
                methods:
                    - GET
                strip_path: false
                https_redirect_status_code: 426
                path_handling: v0
        plugins:
            -
                name: jwt-keycloak
                tags:
                    - ns.gw-b8244
                enabled: true
                config:
                    allowed_iss:
                        - 'http://keycloak.localtest.me:9080/auth/realms/master'
                    run_on_preflight: true
                    iss_key_grace_period: 10
                    maximum_expiration: 0
                    algorithm: RS256
                    claims_to_verify:
                        - exp
                    uri_param_names:
                        - jwt
                    cookie_names: []
                    scope: null
                    roles: null
                    realm_roles: null
                    client_roles:
                        - 'cypress-auth-profile:read'
                    anonymous: null
                    consumer_match: true
                    consumer_match_claim: azp
                    consumer_match_claim_custom_id: true
                    consumer_match_ignore_not_found: false
                    allowed_aud: cypress-auth-profile

APS -Portal console log:
apsportal                                 | 2023-11-16 03:56:48 debug: [batch.worker]  -- updated trans (context) undefined -> "{\"message\":\"{actor} {action} {entity} {message}\",\"params\":{\"action\":\"publish\",\"actor\":\"Janis Smith\",\"entity\":\"gateway configuration\",\"message\":\"{\\\"error\\\": \\\"Sync Failed.\\\", \\\"results\\\": \\\"updating route cc-service-for-platform-route  {\\\\n-  \\\\\\\"created_at\\\\\\\": 1.700106615e+09,\\\\n   \\\\\\\"hosts\\\\\\\": [\\\\n     \\\\\\\"cc-service-for-platform.api.gov.bc.ca\\\\\\\"\\\\n   ],\\\\n   \\\\\\\"https_redirect_status_code\\\\\\\": 426,\\\\n   \\\\\\\"id\\\\\\\": \\\\\\\"224899ca-1b3e-49a1-a1ff-31678d1c5e18\\\\\\\",\\\\n   \\\\\\\"methods\\\\\\\": [\\\\n     \\\\\\\"GET\\\\\\\"\\\\n   ],\\\\n   \\\\\\\"name\\\\\\\": \\\\\\\"cc-service-for-platform-route\\\\\\\",\\\\n   \\\\\\\"path_handling\\\\\\\": \\\\\\\"v0\\\\\\\",\\\\n   \\\\\\\"paths\\\\\\\": [\\\\n     \\\\\\\"/\\\\\\\"\\\\n   ],\\\\n   \\\\\\\"preserve_host\\\\\\\": false,\\\\n   \\\\\\\"protocols\\\\\\\": [\\\\n     \\\\\\\"http\\\\\\\",\\\\n     \\\\\\\"https\\\\\\\"\\\\n   ],\\\\n   \\\\\\\"regex_priority\\\\\\\": 0,\\\\n-  \\\\\\\"request_buffering\\\\\\\": true,\\\\n-  \\\\\\\"response_buffering\\\\\\\": true,\\\\n   \\\\\\\"service\\\\\\\": {\\\\n     \\\\\\\"id\\\\\\\": \\\\\\\"6a88bdba-fab3-441f-bc0a-3927d1b233fd\\\\\\\"\\\\n   },\\\\n   \\\\\\\"strip_path\\\\\\\": false,\\\\n   \\\\\\\"tags\\\\\\\": [\\\\n     \\\\\\\"ns.gw-b8244\\\\\\\"\\\\n   ],\\\\n-  \\\\\\\"updated_at\\\\\\\": 1.700106615e+09\\\\n }\\\\n\\\\nupdating plugin jwt-keycloak for service 6a88bdba-fab3-441f-bc0a-3927d1b233fd  {\\\\n   \\\\\\\"config\\\\\\\": {\\\\n     \\\\\\\"algorithm\\\\\\\": \\\\\\\"RS256\\\\\\\",\\\\n     \\\\\\\"allowed_iss\\\\\\\": [\\\\n       \\\\\\\"http://keycloak.localtest.me:9080/auth/realms/master\\\\\\\"\\\\n     ],\\\\n     \\\\\\\"anonymous\\\\\\\": null,\\\\n-    \\\\\\\"cafile\\\\\\\": null,\\\\n     \\\\\\\"claims_to_verify\\\\\\\": [\\\\n       \\\\\\\"exp\\\\\\\"\\\\n     ],\\\\n-    \\\\\\\"client_roles\\\\\\\": null,\\\\n+    \\\\\\\"client_roles\\\\\\\": [\\\\n+      \\\\\\\"cypress-auth-profile:read\\\\\\\"\\\\n+    ],\\\\n     \\\\\\\"consumer_match\\\\\\\": true,\\\\n     \\\\\\\"consumer_match_claim\\\\\\\": \\\\\\\"azp\\\\\\\",\\\\n     \\\\\\\"consumer_match_claim_custom_id\\\\\\\": true,\\\\n     \\\\\\\"consumer_match_ignore_not_found\\\\\\\": false,\\\\n     \\\\\\\"cookie_names\\\\\\\": [\\\\n     ],\\\\n-    \\\\\\\"header_names\\\\\\\": [\\\\n-      \\\\\\\"authorization\\\\\\\"\\\\n-    ],\\\\n     \\\\\\\"iss_key_grace_period\\\\\\\": 10,\\\\n     \\\\\\\"maximum_expiration\\\\\\\": 0,\\\\n     \\\\\\\"realm_roles\\\\\\\": null,\\\\n     \\\\\\\"roles\\\\\\\": null,\\\\n     \\\\\\\"run_on_preflight\\\\\\\": true,\\\\n     \\\\\\\"scope\\\\\\\": null,\\\\n     \\\\\\\"uri_param_names\\\\\\\": [\\\\n       \\\\\\\"jwt\\\\\\\"\\\\n     ],\\\\n-    \\\\\\\"well_known_template\\\\\\\": \\\\\\\"%s/.well-known/openid-configuration\\\\\\\"\\\\n+    \\\\\\\"allowed_aud\\\\\\\": \\\\\\\"cypress-auth-profile\\\\\\\"\\\\n   },\\\\n-  \\\\\\\"created_at\\\\\\\": 1.700096791e+09,\\\\n   \\\\\\\"enabled\\\\\\\": true,\\\\n   \\\\\\\"id\\\\\\\": \\\\\\\"97c22349-5b1a-45e6-ada6-cfec63ebc9a1\\\\\\\",\\\\n   \\\\\\\"name\\\\\\\": \\\\\\\"jwt-keycloak\\\\\\\",\\\\n-  \\\\\\\"protocols\\\\\\\": [\\\\n-    \\\\\\\"grpc\\\\\\\",\\\\n-    \\\\\\\"grpcs\\\\\\\",\\\\n-    \\\\\\\"http\\\\\\\",\\\\n-    \\\\\\\"https\\\\\\\"\\\\n-  ],\\\\n   \\\\\\\"service\\\\\\\": {\\\\n     \\\\\\\"id\\\\\\\": \\\\\\\"6a88bdba-fab3-441f-bc0a-3927d1b233fd\\\\\\\"\\\\n   },\\\\n   \\\\\\\"tags\\\\\\\": [\\\\n     \\\\\\\"ns.gw-b8244\\\\\\\"\\\\n   ]\\\\n }\\\\n\\\\nSummary:\\\\n  Created: 0\\\\n  Updated: 1\\\\n  Deleted: 0\\\\nError: 1 errors occurred:\\\\n\\\\twhile processing event: {Update} plugin jwt-keycloak for service 6a88bdba-fab3-441f-bc0a-3927d1b233fd failed: HTTP status 400 (message: \\\\\\\"schema violation (config.allowed_aud: unknown field)\\\\\\\")\\\\n\\\\n\\\"}\",\"result\":\"failed\"}}"
apsportal                                 | 2023-11-16 03:56:48 debug: [batch.worker]  -- changed trans? (blob)
apsportal                                 | 2023-11-16 03:56:48 debug: [batch.worker] CHILDREN [blob] []
apsportal                                 | 2023-11-16 03:56:48 debug: [batch.worker] {"id":"126","type":"GatewayConfig","name":"N/A","action":"publish","result":"received","message":"publish gateway configuration","refId":"","namespace":"gw-b8244","blob":null,"filterKey1":"namespace:gw-b8244","filterKey2":null,"filterKey3":null,"filterKey4":null,"extRefId":"883ee240-669f-4830-a8fe-ffa677dfc20d","actor":null}
apsportal                                 | 2023-11-16 03:56:48 info: [batch.worker] [Activity] [126] keys triggering update ["result","context"]
apsportal                                 | 2023-11-16 03:56:48 debug: [ks.batch] [update] : Activity 126
apsportal                                 | 2023-11-16 03:56:48 debug: [ks.batch] [update] RESULT {"data":{"updateActivity":{"id":"126"}}}
gwa-api                                   | 2023-11-16 03:56:48,823 [ 16]  INFO portal         : Request Record Activity http://apsportal.localtest.me:3000 : 200
gwa-api                                   | 2023-11-16 03:56:48,824 [ 16] DEBUG app            : Rendered in 0.35596141300266027s

**Comment by ikethecoder** [comment]
@nirajCITZ The jwt-keycloak plugin has not been fully updated - can you remove the "allow_aud" attribute from your config and proceed without it?

**Comment by ikethecoder** [comment]
@nirajCITZ There is a new version of Kong that you can use to retest `ghcr.io/bcgov-dss/api-serv-infra/kong3:3.6-9af812f1`

**Comment by ikethecoder** [comment]
Retested and resolved.
