### ISSUE TITLE
Button not displayed when logged in

### ISSUE THREAD

**Issue by Elson9** [bcgov/api-services-portal#973]
# API Services Portal Issue

This is for the BC Address Geocoder Web Service.
Button is displayed instead of a link only when not logged in. Should also be a link for consistency.
LOC is also requesting the order of products is changed, with BC Address Geocoder (Public) first.

## User Story

**As a** _< persona >_,<br>
**I want** _< feature >_<br>
**so that** _< reason >_.

| **As A**      | **I Want**    | **So that**  |
| ------------- | ------------- | ------------ |
| _< persona >_ | _< feature >_ | _< reason >_ |

### ENV

- [ ] `DEV`
- [x] `TEST`
- [x] `PROD`

### TESTCASE

-

### EXPECTED

![image](https://github.com/bcgov/api-services-portal/assets/17093989/babce7f1-a6b5-42c5-9ab2-2ba4f352059a)

### ACTUAL

![image](https://github.com/bcgov/api-services-portal/assets/17093989/9ce518e6-f781-4778-a868-90ad8191414f)

**Comment by Jonesy** [comment]
@Elson9 you can customize the appearance set here https://github.com/bcgov/api-services-portal/blob/dev/src/nextapp/components/access-request-form/access-request-dialog.tsx#L40 with this prop https://github.com/bcgov/api-services-portal/blob/dev/src/nextapp/components/access-request-form/access-request-dialog.tsx#L40

**Comment by Elson9** [comment]
Fixed here: https://github.com/bcgov/api-services-portal/commit/99e6cb80e550e40a6b67169c54215ba278a20ab4

**Comment by Elson9** [comment]
Updated fix here: https://github.com/bcgov/api-services-portal/commit/893c0e9cd8930cb467d4068152597ae2dc7afa4b
