### ISSUE TITLE
Consumer app and app owner metadata

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#980]
This ticket is for work to add the Application and Application Owner as metadata to the Consumer record so that it is available in the enhanced analytics.

**Comment by ikethecoder** [comment]
The change involves:
- Adding a parameter for `tags` to the function https://github.com/bcgov/api-services-portal/blob/dev/src/services/kong/consumer-service.ts#L60 and using those values to be populated for the Consumer
- Update the callers of this `createKongConsumer` function to prepare the tags using the corresponding application and application owner, where the tags will have the format: `[ ``app:${app.name}``, ``owner:${app.owner.name}`` ]`

**Comment by Elson9** [comment]
Draft pull request created: #1011

**Comment by Elson9** [comment]
Fixed in #1028
